// <auto-generated />
using System;
using Locadora.Api.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Locadora.Api.Infra.Data.Migrations
{
    [DbContext(typeof(LocadoraContext))]
    [Migration("20231004225106_InitialDataMig")]
    partial class InitialDataMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Locadora.Api.Domain.Entities.MovimentacoesVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Mov_MovimentacoesVeiculoId");

                    b.Property<DateTimeOffset>("DateAlter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateInc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Mov_Descricao");

                    b.Property<int>("MovimentacaoVeiculo")
                        .HasColumnType("integer");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("Vei_VeiculoId");

                    b.HasKey("Id")
                        .HasName("PK_Mov_MovimentacoesVeiculoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Mov_MovimentacoesVeiculo", "Locadora");
                });

            modelBuilder.Entity("Locadora.Api.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Vei_VeiculoId");

                    b.Property<DateTimeOffset>("DateAlter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateInc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Vei_Placa");

                    b.Property<int>("StatusVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("Vei_Status");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("Vei_Tipo");

                    b.HasKey("Id")
                        .HasName("PK_Vei_Veiculo");

                    b.ToTable("Vei_Veiculo", "Locadora");
                });

            modelBuilder.Entity("Locadora.Api.Domain.Entities.MovimentacoesVeiculo", b =>
                {
                    b.HasOne("Locadora.Api.Domain.Entities.Veiculo", "Veiculo")
                        .WithMany("MovimentacaoVeiculo")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Locadora.Api.Domain.Entities.Veiculo", b =>
                {
                    b.Navigation("MovimentacaoVeiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
