// <auto-generated />
using System;
using Locadora.Api.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Locadora.Api.Infra.Data.Migrations
{
    [DbContext(typeof(LocadoraContext))]
    [Migration("20231004021533_AjustesEntities")]
    partial class AjustesEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Locadora.Api.Domain.Entities.MovimentacoesVeiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CascadeMode")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLevelCascadeMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateAlter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateInc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MovimentacaoVeiculo")
                        .HasColumnType("integer");

                    b.Property<int>("RuleLevelCascadeMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MovimentacoesVeiculos");
                });

            modelBuilder.Entity("Locadora.Api.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CascadeMode")
                        .HasColumnType("integer");

                    b.Property<int>("ClassLevelCascadeMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateAlter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateInc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovimentacoesVeiculoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuleLevelCascadeMode")
                        .HasColumnType("integer");

                    b.Property<int>("StatusVeiculo")
                        .HasColumnType("integer");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovimentacoesVeiculoId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("Locadora.Api.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("Locadora.Api.Domain.Entities.MovimentacoesVeiculo", "MovimentacoesVeiculo")
                        .WithMany("Veiculos")
                        .HasForeignKey("MovimentacoesVeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovimentacoesVeiculo");
                });

            modelBuilder.Entity("Locadora.Api.Domain.Entities.MovimentacoesVeiculo", b =>
                {
                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
